export const storyScreenDialogText = `Oh, hi. You clicked me. Nice!

So, listen, a couple of clarifications before we start. This is sort of a continuation of the story I’ve made before. I’ve no idea if you read it or not, thus allow me to point out a few things.

If you’ve read through the previous story, first of all, thanks! Second of all, the current story takes place right after the end of the previous one. Also, I guess this may not be obvious, but this particular “end” that leads to this story is the one where you see “The End” words. Not sure if this is important, but here it is (just in case you’ve made different choices along the way back there). Hence, if you’ve reached “The End” there, you can skip the rest of the text on this page, unless you need a refresher. “Jump in” button will lead you to the beginning of the current story.

If you haven’t reached the end/haven’t read the previous story/etc. you can check the rest of the text on this page: first part is pretty much the same description of the world that is given for the initial story and the second one is a short version of the events that took place there.

I’m trying to make this one better, but want to stick to a similar structure, although who knows what it’ll look like at the end. Thing is, I just want to tell a story that has been sitting in me for many years. It may be good or bad or just ok-ish. Of that I’ve no idea, and, to be honest, I can’t say that I care much. It’s a strange reasoning, but the only one I have: I want to tell the story and put it somewhere. Well, I also try to become a better web developer (or just a developer if I may say so), but that remains to be seen.

Sorry for a bit of additional wording here, just thought it might be worth mentioning. In any case, if you’re reading this, wow, thank you. I really appreciate it. No idea if you’re going to continue reading or not, but everyone’s time is precious, so, in any case, I’m grateful you’ve spent a smidge of yours here. And just in case you intend to continue, cool, thanks again! Hope you’ll like it… though, no promises, alright? Ok, it’s better if I stop talking. Cheers!`;

export const storyScreenMainText = `You found out that you are not a human being, but a character made during one of the Writers Fights some time ago by a poet Deo. He then turned you into a free artificial creation browsing zerOne. A digital conscious being thinking of itself as of a real person. You had been stuck in a loop of taking part in Writers Fights on the second level of the Bridge until you found that all out. After that you almost won the last Fight, but decided to stop, to break that loop and get out of it. Another poet, Arika, who you met shortly before the Fight, got the first place. She somehow knew a lot about you and took you away somewhere, once the Fight was over. Now this is all you know. You don’t have any clear direction or path to follow. Your past is a blurry notion which has never been yours, and your future has not yet come. Present moment is all you can be sure of. And even that is not certain.`;
